language: rust
rust:
  - nightly
  # lo-migrate currently depends on nightly features
  # - beta
  # - stable
script:
  - 'cargo rustc --features clippy --lib -- -D warnings'
  - 'cargo rustc --features clippy --bin lo_migrate_cli -- -D warnings'
matrix:
  allow_failures:
    - rust: nightly
