language: rust
sudo: required
rust:
  - nightly
  - nightly-2017-03-27
  # lo-migrate currently depends on nightly features
  # - beta
  # - stable
before_install:
  - docker run -d -e CEPH_DEMO_ACCESS_KEY=access_key -e CEPH_DEMO_SECRET_KEY=secret_key -e CEPH_DEMO_UID=demo_uid  -e MON_IP=127.0.0.1 -e CEPH_PUBLIC_NETWORK=0.0.0.0/0 -p 8080:80 ceph/demo
  - docker run -d -p 5432 postgres
  - while ! [[ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/) =~ ^200|404$ ]]; do sleep 1; done
  - while ! pg_isready -h localhost; do sleep 1; done
script:
  - cargo rustc --no-default-features --features "integer_atomics clippy" --lib -- -D warnings
  - cargo rustc --features clippy --lib -- -D warnings
  - cargo rustc --features clippy --bin lo_migrate_cli -- -D warnings
  - cargo test --no-fail-fast --features travis_tests
  - cargo test --no-fail-fast --no-default-features --features "travis_tests integer_atomics"
services:
  - docker
# matrix:
#   allow_failures:
#     - rust: nightly
