[package]
name = "lo_migrate"
version = "0.1.0"
authors = ["Peter Gerber <peter@arbitrary.ch>"]

[dependencies]
clap = "2.22"
chrono = "0.3"
derive-error = "0.0"
digest = "0.4"
fallible-iterator = "0.1"
sha2 = "0.4"
postgres = "0.13"
postgres_large_object = "0.5"
aws-sdk-rust = "0.1"
rustc-serialize = "0.3"
two-lock-queue = "0.1"
clippy = { version = "*", optional = true }
mkstemp-rs = "0.0"
memmap = "0.5"
hyper = "0.10"
base64 = "0.4"
log = "0.3"
env_logger = "0.4"
url = "1.4"
hyper-rustls = "0.3"

[dev-dependencies]
rand = "0.3"
regex = "0.2"

[replace]
# doesn't build using Nightly but we need nightly for the atomic integers
"lsio:0.1.17" = { git = "https://github.com/pgerber/lsio", branch = "nightly_0_1_17" }

[features]
travis_tests = ["postgres_tests", "s3_tests"]
postgres_tests = []
s3_tests = []
try_from = []
integer_atomics = []
unstable = ["try_from", "integer_atomics"]
default = ["unstable"]

[[bin]]
name = "lo_migrate_cli"
test = false
doc = false
