[package]
name = "lo_migrate"
version = "0.1.0"
authors = ["Peter Gerber <peter@arbitrary.ch>"]

[dependencies]
digest = "*"
sha1 = { version = "*", git = "https://github.com/RustCrypto/hashes" }
sha2 = "*"
postgres = "0.13"
postgres_large_object = "0.5.1"
aws-sdk-rust = "*"
rustc-serialize = "*"
two-lock-queue = "*"
clippy = { version = "*", optional = true }
mktemp = "*"
memmap = "*"
hyper = "*"
base64 = "*"
log = "*"
env_logger = "*"
url = "*"
lazy_static = "*"

[features]
default = []
# dev = ["clippy"]

[[bin]]
name = "lo_migrate_cli"
test = false
doc = false
