[package]
name = "lo_migrate"
version = "0.1.0"
authors = ["Peter Gerber <peter@arbitrary.ch>"]

[dependencies]
clap = "*"
chrono = "*"
digest = "*"
fallible-iterator = "*"
sha1 = { version = "*", git = "https://github.com/RustCrypto/hashes" }
sha2 = "*"
spin = "*"
postgres = "0.13"
postgres_large_object = "0.5"
aws-sdk-rust = "*"
rustc-serialize = "*"
two-lock-queue = "*"
clippy = { version = "*", optional = true }
mktemp = "*"
memmap = "*"
hyper = "*"
base64 = "*"
log = "*"
env_logger = "*"
url = "*"
hyper-rustls = "*"

[dev-dependencies]
rand = "0.3"
regex = "0.2"

[replace]
# doesn't build Rust Nightly but we need nightly for the atomic integers
"lsio:0.1.17" = { git = "https://github.com/pgerber/lsio", branch = "nightly_0_1_17" }

[features]
travis_tests = ["postgres_tests", "s3_tests"]
postgres_tests = []
s3_tests = []
default = []

[[bin]]
name = "lo_migrate_cli"
test = false
doc = false
